version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nextjs-db
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:4.4
    container_name: mongo
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  mongo-data:
